msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2013-03-22 11:22+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: DOMAIN\n"

#. Default: "More than one location found, chose first match \"${place}\". Please check that coordinates are correct."
#: ./ftw/geo/handlers.py:44
msgid "msg_multiple_matches"
msgstr "Plus d'un lieu trouvé. Le premier résultat \"${place}\" a été choisie. Veuillez vérifier si les coordonnées sont correctes."

#. Default: "Geocoding failed because of a network error."
#: ./ftw/geo/handlers.py:68
msgid "msg_network_error"
msgstr "Le géocodage n'a pas pu être effectuée en raison d'une erreur réseau."

#. Default: "Couldn't find a suitable match for location \"${location}\". Please use the \"coordinates\" tab to manually set the correct map loaction."
#: ./ftw/geo/handlers.py:52
msgid "msg_no_match"
msgstr "Impossible de trouver un résultat compatible pour le lieu \"${location}\". S'il vous plaît utilisez l'onglet \"coordonnées\" pour mettre la section de carte manuellement"

#. Default: "Geocoding failed because daily query limit has been exceeded."
#: ./ftw/geo/handlers.py:61
msgid "msg_too_many_queries"
msgstr "Le géocodage a échoué parce que la limite quotidienne de requêtes a été dépassé."

#. Default: "Geocoding failed because of an error: ${ecxeption}"
#: ./ftw/geo/handlers.py:76
msgid "msg_unhandled_exception"
msgstr "Le géocodage a échoué: ${ecxeption}"


